version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop  
    volumes:
      - ./laptop:/usr/src/app 
    ports:
      - 5011:80  # host:container
    environment: 
      MONGODB_HOSTNAME: db
    depends_on: 
      - db

  website:
    image: php:apache
    volumes:
      - ./website:/var/www/html
    ports:
      - 5010:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running

  web:
    build: ./brevetsapp
    command: python -u flask_brevets.py
    ports:
      - "5012:5000"
    volumes:
      - ./brevetsapp:/index
    environment: 
      MONGODB_HOSTNAME: db
    depends_on: 
      - db

  db:
    image: mongo
